# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_person_python_sdk import schemas  # noqa: F401


class ContactUsage1089da0ab90910000fa7748617db0898(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class usedFor(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['UsageBehavior1089da0ab90910000fa6c19789ce0896']:
                                return UsageBehavior1089da0ab90910000fa6c19789ce0896
                    
                        def __new__(
                            cls,
                            arg: typing.Union[typing.Tuple['UsageBehavior1089da0ab90910000fa6c19789ce0896'], typing.List['UsageBehavior1089da0ab90910000fa6c19789ce0896']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'usedFor':
                            return super().__new__(
                                cls,
                                arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'UsageBehavior1089da0ab90910000fa6c19789ce0896':
                            return super().__getitem__(i)
                    comment = schemas.StrSchema
                    primary = schemas.BoolSchema
                    public = schemas.BoolSchema
                
                    @staticmethod
                    def usageType() -> typing.Type['UsageType51665e7371e310000f554a00d31000f2']:
                        return UsageType51665e7371e310000f554a00d31000f2
                    __annotations__ = {
                        "usedFor": usedFor,
                        "comment": comment,
                        "primary": primary,
                        "public": public,
                        "usageType": usageType,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["usedFor"]) -> MetaOapg.properties.usedFor: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["primary"]) -> MetaOapg.properties.primary: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["public"]) -> MetaOapg.properties.public: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["usageType"]) -> 'UsageType51665e7371e310000f554a00d31000f2': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["usedFor", "comment", "primary", "public", "usageType", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["usedFor"]) -> typing.Union[MetaOapg.properties.usedFor, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> typing.Union[MetaOapg.properties.comment, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["primary"]) -> typing.Union[MetaOapg.properties.primary, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["public"]) -> typing.Union[MetaOapg.properties.public, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["usageType"]) -> typing.Union['UsageType51665e7371e310000f554a00d31000f2', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["usedFor", "comment", "primary", "public", "usageType", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                usedFor: typing.Union[MetaOapg.properties.usedFor, list, tuple, schemas.Unset] = schemas.unset,
                comment: typing.Union[MetaOapg.properties.comment, str, schemas.Unset] = schemas.unset,
                primary: typing.Union[MetaOapg.properties.primary, bool, schemas.Unset] = schemas.unset,
                public: typing.Union[MetaOapg.properties.public, bool, schemas.Unset] = schemas.unset,
                usageType: typing.Union['UsageType51665e7371e310000f554a00d31000f2', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    usedFor=usedFor,
                    comment=comment,
                    primary=primary,
                    public=public,
                    usageType=usageType,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ContactUsage1089da0ab90910000fa7748617db0898':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_person_python_sdk.model.usage_behavior1089da0ab90910000fa6c19789ce0896 import UsageBehavior1089da0ab90910000fa6c19789ce0896
from workday_person_python_sdk.model.usage_type51665e7371e310000f554a00d31000f2 import UsageType51665e7371e310000f554a00d31000f2
