# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_person_python_sdk import schemas  # noqa: F401


class EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    hispanicOrLatinoForVisualSurvey = schemas.BoolSchema
                    
                    
                    class ethnicities(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['Ethnicity6de928ab1284100058892e53dac501d1']:
                                return Ethnicity6de928ab1284100058892e53dac501d1
                    
                        def __new__(
                            cls,
                            arg: typing.Union[typing.Tuple['Ethnicity6de928ab1284100058892e53dac501d1'], typing.List['Ethnicity6de928ab1284100058892e53dac501d1']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'ethnicities':
                            return super().__new__(
                                cls,
                                arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'Ethnicity6de928ab1284100058892e53dac501d1':
                            return super().__getitem__(i)
                    __annotations__ = {
                        "hispanicOrLatinoForVisualSurvey": hispanicOrLatinoForVisualSurvey,
                        "ethnicities": ethnicities,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["hispanicOrLatinoForVisualSurvey"]) -> MetaOapg.properties.hispanicOrLatinoForVisualSurvey: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["ethnicities"]) -> MetaOapg.properties.ethnicities: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["hispanicOrLatinoForVisualSurvey", "ethnicities", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["hispanicOrLatinoForVisualSurvey"]) -> typing.Union[MetaOapg.properties.hispanicOrLatinoForVisualSurvey, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["ethnicities"]) -> typing.Union[MetaOapg.properties.ethnicities, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["hispanicOrLatinoForVisualSurvey", "ethnicities", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                hispanicOrLatinoForVisualSurvey: typing.Union[MetaOapg.properties.hispanicOrLatinoForVisualSurvey, bool, schemas.Unset] = schemas.unset,
                ethnicities: typing.Union[MetaOapg.properties.ethnicities, list, tuple, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    hispanicOrLatinoForVisualSurvey=hispanicOrLatinoForVisualSurvey,
                    ethnicities=ethnicities,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_person_python_sdk.model.ethnicity6de928ab1284100058892e53dac501d1 import Ethnicity6de928ab1284100058892e53dac501d1
