# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.usage_behavior1089da0ab90910000fa6c19789ce0896 import UsageBehavior1089da0ab90910000fa6c19789ce0896
from workday_person_python_sdk.type.usage_type51665e7371e310000f554a00d31000f2 import UsageType51665e7371e310000f554a00d31000f2

ContactUsage1089da0ab90910000fa7748617db0898 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
