# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.city_ab827579ee1710002095f51c0e3f0178 import CityAb827579ee1710002095f51c0e3f0178

CountryCityA58f621b14ee1000146a333da1c900e6 = typing.Union[CityAb827579ee1710002095f51c0e3f0178,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
