# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.person_localized_name_component_format51f9e585eec710001050c68b768b00ea import PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00ea

class RequiredCountriesGetNameComponentsResponse(TypedDict):
    pass

class OptionalCountriesGetNameComponentsResponse(TypedDict, total=False):
    data: typing.List[PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00ea]

    total: int

class CountriesGetNameComponentsResponse(RequiredCountriesGetNameComponentsResponse, OptionalCountriesGetNameComponentsResponse):
    pass
