# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredERRORMODELREFERENCE(TypedDict):
    # A description of the error
    error: str

class OptionalERRORMODELREFERENCE(TypedDict, total=False):
    # The code that corresponds to the error message. Use the error code to drive programmatic error-handling behavior. Don't use error message strings for this purpose because they are subject to change
    code: str

    # The field related to the error
    field: str

    # The path of the field related to the error
    path: str

class ERRORMODELREFERENCE(RequiredERRORMODELREFERENCE, OptionalERRORMODELREFERENCE):
    pass
