# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.ethnicities_for_visual_survey_ebff7995b021100014bbd5c6cff700ae import EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae

EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104 = typing.Union[EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
