# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.facetsmodelreference_item_values import FACETSMODELREFERENCEItemValues

class RequiredFACETSMODELREFERENCEItem(TypedDict):
    pass

class OptionalFACETSMODELREFERENCEItem(TypedDict, total=False):
    # A description of the facet
    descriptor: str

    # The alias used to select the facet
    facetParameter: str

    values: FACETSMODELREFERENCEItemValues

class FACETSMODELREFERENCEItem(RequiredFACETSMODELREFERENCEItem, OptionalFACETSMODELREFERENCEItem):
    pass
