# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredINSTANCEMODELREFERENCE(TypedDict):
    # wid / id / reference id
    id: str

class OptionalINSTANCEMODELREFERENCE(TypedDict, total=False):
    # A description of the instance
    descriptor: str

    # A link to the instance
    href: str

class INSTANCEMODELREFERENCE(RequiredINSTANCEMODELREFERENCE, OptionalINSTANCEMODELREFERENCE):
    pass
