# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.military_discharge_type_b15af3935f8910001f7585a44c0b0000 import MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000

MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000 = typing.Union[MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
