# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.military_service_reference_aaeb64c958b2100016889fe0267e0246 import MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246

MilitaryServiceReference6de928ab128410005b41e4b2f27d021e = typing.Union[MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
