# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.phone_reference_df014bc8b5fa10000af0fe7cb0ab00dd import PhoneReferenceDf014bc8b5fa10000af0fe7cb0ab00dd

class RequiredPeopleGetWorkPhonesResponse(TypedDict):
    pass

class OptionalPeopleGetWorkPhonesResponse(TypedDict, total=False):
    data: typing.List[PhoneReferenceDf014bc8b5fa10000af0fe7cb0ab00dd]

    total: int

class PeopleGetWorkPhonesResponse(RequiredPeopleGetWorkPhonesResponse, OptionalPeopleGetWorkPhonesResponse):
    pass
