# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.email_reference9c3ab7b846e41000327e788d9664012a import EmailReference9c3ab7b846e41000327e788d9664012a

class RequiredPeopleGetWorkEmailsResponse(TypedDict):
    pass

class OptionalPeopleGetWorkEmailsResponse(TypedDict, total=False):
    data: typing.List[EmailReference9c3ab7b846e41000327e788d9664012a]

    total: int

class PeopleGetWorkEmailsResponse(RequiredPeopleGetWorkEmailsResponse, OptionalPeopleGetWorkEmailsResponse):
    pass
