# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.media_download5d5f0fb1184b10000b16f0e5c20f0000 import MediaDownload5d5f0fb1184b10000b16f0e5c20f0000

class RequiredPeopleGetNamePronunciationsResponse(TypedDict):
    pass

class OptionalPeopleGetNamePronunciationsResponse(TypedDict, total=False):
    data: typing.List[MediaDownload5d5f0fb1184b10000b16f0e5c20f0000]

    total: int

class PeopleGetNamePronunciationsResponse(RequiredPeopleGetNamePronunciationsResponse, OptionalPeopleGetNamePronunciationsResponse):
    pass
