# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.person_public_representation_d8f2aecf3d63100016a77ab413a20235 import PersonPublicRepresentationD8f2aecf3d63100016a77ab413a20235

class RequiredPeopleGetPublicContactInformationResponse(TypedDict):
    pass

class OptionalPeopleGetPublicContactInformationResponse(TypedDict, total=False):
    data: typing.List[PersonPublicRepresentationD8f2aecf3d63100016a77ab413a20235]

    total: int

class PeopleGetPublicContactInformationResponse(RequiredPeopleGetPublicContactInformationResponse, OptionalPeopleGetPublicContactInformationResponse):
    pass
