# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.address_reference9c3ab7b846e4100009e5ec55fa530024 import AddressReference9c3ab7b846e4100009e5ec55fa530024

class RequiredPeopleGetWorkAddressesResponse(TypedDict):
    pass

class OptionalPeopleGetWorkAddressesResponse(TypedDict, total=False):
    data: typing.List[AddressReference9c3ab7b846e4100009e5ec55fa530024]

    total: int

class PeopleGetWorkAddressesResponse(RequiredPeopleGetWorkAddressesResponse, OptionalPeopleGetWorkAddressesResponse):
    pass
