# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.military_rank6de928ab128410005be5dbfb939d0234 import MilitaryRank6de928ab128410005be5dbfb939d0234

Rank6de928ab128410005b41e4ba56a6021f = typing.Union[MilitaryRank6de928ab128410005be5dbfb939d0234,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
