# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.relative_type_e08d883b5eae100003cff859e1ec02dd import RelativeTypeE08d883b5eae100003cff859e1ec02dd

RelativeTypeE08d883b5eae1000040cc1231a5902f5 = typing.Union[RelativeTypeE08d883b5eae100003cff859e1ec02dd,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
