# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.universal_id814af6e5b9fa100022bff92eb5140117 import UniversalID814af6e5b9fa100022bff92eb5140117

UniversalIDE451ce2c8b48100007c31392a1ff00c2 = typing.Union[UniversalID814af6e5b9fa100022bff92eb5140117,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
