# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_person_python_sdk.type.work_address_reference_c1bb9f46f65210002d2fa259a1c10095 import WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095

class RequiredWorkContactInformationChangesGetAddressesStagedResponse(TypedDict):
    pass

class OptionalWorkContactInformationChangesGetAddressesStagedResponse(TypedDict, total=False):
    data: typing.List[WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095]

    total: int

class WorkContactInformationChangesGetAddressesStagedResponse(RequiredWorkContactInformationChangesGetAddressesStagedResponse, OptionalWorkContactInformationChangesGetAddressesStagedResponse):
    pass
