# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.ethnicities_for_visual_survey_ebff7995b021100014bbd5c6cff700ae import EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae
from workday_person_python_sdk import configuration


class TestEthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae(unittest.TestCase):
    """EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
