# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country_and_nationality06544db2578d10000ec1cd4257350000 import CountryAndNationality06544db2578d10000ec1cd4257350000
from workday_person_python_sdk import configuration


class TestCountryAndNationality06544db2578d10000ec1cd4257350000(unittest.TestCase):
    """CountryAndNationality06544db2578d10000ec1cd4257350000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
