# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.work_contact_information_changes_get_staged_email_addresses_response import WorkContactInformationChangesGetStagedEmailAddressesResponse
from workday_person_python_sdk import configuration


class TestWorkContactInformationChangesGetStagedEmailAddressesResponse(unittest.TestCase):
    """WorkContactInformationChangesGetStagedEmailAddressesResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
