# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.certification_basis6de928ab128410005c56a638b9d4024c import CertificationBasis6de928ab128410005c56a638b9d4024c
from workday_person_python_sdk import configuration


class TestCertificationBasis6de928ab128410005c56a638b9d4024c(unittest.TestCase):
    """CertificationBasis6de928ab128410005c56a638b9d4024c unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
