# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.primary_nationality2b5dded3d48e100013b87a5e15b3012a import PrimaryNationality2b5dded3d48e100013b87a5e15b3012a
from workday_person_python_sdk import configuration


class TestPrimaryNationality2b5dded3d48e100013b87a5e15b3012a(unittest.TestCase):
    """PrimaryNationality2b5dded3d48e100013b87a5e15b3012a unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
