# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.aboriginal_indigenous_identification37580627f49d10002587d93d0a820000 import AboriginalIndigenousIdentification37580627f49d10002587d93d0a820000
from workday_person_python_sdk import configuration


class TestAboriginalIndigenousIdentification37580627f49d10002587d93d0a820000(unittest.TestCase):
    """AboriginalIndigenousIdentification37580627f49d10002587d93d0a820000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
