# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.gender6de928ab12841000544f9cd350c201b9 import Gender6de928ab12841000544f9cd350c201b9
from workday_person_python_sdk import configuration


class TestGender6de928ab12841000544f9cd350c201b9(unittest.TestCase):
    """Gender6de928ab12841000544f9cd350c201b9 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
