# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.instant_messenger_account33e26848dc00100036f723337ebb0132 import InstantMessengerAccount33e26848dc00100036f723337ebb0132
from workday_person_python_sdk import configuration


class TestInstantMessengerAccount33e26848dc00100036f723337ebb0132(unittest.TestCase):
    """InstantMessengerAccount33e26848dc00100036f723337ebb0132 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
