# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.web_address33e26848dc0010003893a0202ced0165 import WebAddress33e26848dc0010003893a0202ced0165
from workday_person_python_sdk import configuration


class TestWebAddress33e26848dc0010003893a0202ced0165(unittest.TestCase):
    """WebAddress33e26848dc0010003893a0202ced0165 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
