# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country8beeb162738910001433a1ef009a01d0 import Country8beeb162738910001433a1ef009a01d0
from workday_person_python_sdk import configuration


class TestCountry8beeb162738910001433a1ef009a01d0(unittest.TestCase):
    """Country8beeb162738910001433a1ef009a01d0 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
