# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_type_c1bb9f46f65210002d3c343d773200bc import UsageTypeC1bb9f46f65210002d3c343d773200bc
from workday_person_python_sdk import configuration


class TestUsageTypeC1bb9f46f65210002d3c343d773200bc(unittest.TestCase):
    """UsageTypeC1bb9f46f65210002d3c343d773200bc unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
