# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.religious_suffix_e08d883b5eae10000403d7eb401e02f2 import ReligiousSuffixE08d883b5eae10000403d7eb401e02f2
from workday_person_python_sdk import configuration


class TestReligiousSuffixE08d883b5eae10000403d7eb401e02f2(unittest.TestCase):
    """ReligiousSuffixE08d883b5eae10000403d7eb401e02f2 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
