# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.home_contact_information_changes_get_phone_numbers_response import HomeContactInformationChangesGetPhoneNumbersResponse
from workday_person_python_sdk import configuration


class TestHomeContactInformationChangesGetPhoneNumbersResponse(unittest.TestCase):
    """HomeContactInformationChangesGetPhoneNumbersResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
