# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_behavior1089da0ab90910000fa6c19789ce0896 import UsageBehavior1089da0ab90910000fa6c19789ce0896
from workday_person_python_sdk import configuration


class TestUsageBehavior1089da0ab90910000fa6c19789ce0896(unittest.TestCase):
    """UsageBehavior1089da0ab90910000fa6c19789ce0896 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
