# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.phone_device_type1089da0ab90910000f85ace9e4050892 import PhoneDeviceType1089da0ab90910000f85ace9e4050892
from workday_person_python_sdk import configuration


class TestPhoneDeviceType1089da0ab90910000f85ace9e4050892(unittest.TestCase):
    """PhoneDeviceType1089da0ab90910000f85ace9e4050892 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
