# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country_c1bb9f46f65210002d2fa329fe6700b4 import CountryC1bb9f46f65210002d2fa329fe6700b4
from workday_person_python_sdk import configuration


class TestCountryC1bb9f46f65210002d2fa329fe6700b4(unittest.TestCase):
    """CountryC1bb9f46f65210002d2fa329fe6700b4 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
