# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country81f66ab16f7510005c53d8fd5f5b4852 import Country81f66ab16f7510005c53d8fd5f5b4852
from workday_person_python_sdk import configuration


class TestCountry81f66ab16f7510005c53d8fd5f5b4852(unittest.TestCase):
    """Country81f66ab16f7510005c53d8fd5f5b4852 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
