# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.phone_reference1089da0ab90910000f70891a998b0887 import PhoneReference1089da0ab90910000f70891a998b0887
from workday_person_python_sdk import configuration


class TestPhoneReference1089da0ab90910000f70891a998b0887(unittest.TestCase):
    """PhoneReference1089da0ab90910000f70891a998b0887 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
