# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.social11c67b72c9c610000edf72e003d1004e import Social11c67b72c9c610000edf72e003d1004e
from workday_person_python_sdk import configuration


class TestSocial11c67b72c9c610000edf72e003d1004e(unittest.TestCase):
    """Social11c67b72c9c610000edf72e003d1004e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
