# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country1089da0ab90910000f6e4df524710885 import Country1089da0ab90910000f6e4df524710885
from workday_person_python_sdk import configuration


class TestCountry1089da0ab90910000f6e4df524710885(unittest.TestCase):
    """Country1089da0ab90910000f6e4df524710885 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
