# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_de08a6c876a810000cb2e3d738be0019 import UsageDe08a6c876a810000cb2e3d738be0019
from workday_person_python_sdk import configuration


class TestUsageDe08a6c876a810000cb2e3d738be0019(unittest.TestCase):
    """UsageDe08a6c876a810000cb2e3d738be0019 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
