# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.phone_number_validation_db1991f2fb091000169c5dfa023800b8 import PhoneNumberValidationDb1991f2fb091000169c5dfa023800b8
from workday_person_python_sdk import configuration


class TestPhoneNumberValidationDb1991f2fb091000169c5dfa023800b8(unittest.TestCase):
    """PhoneNumberValidationDb1991f2fb091000169c5dfa023800b8 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
