# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country33e26848dc0010002f1ae802adc30074 import Country33e26848dc0010002f1ae802adc30074
from workday_person_python_sdk import configuration


class TestCountry33e26848dc0010002f1ae802adc30074(unittest.TestCase):
    """Country33e26848dc0010002f1ae802adc30074 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
