# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.social_benefits_locality80df32d43a5810000ce182cac97500bf import SocialBenefitsLocality80df32d43a5810000ce182cac97500bf
from workday_person_python_sdk import configuration


class TestSocialBenefitsLocality80df32d43a5810000ce182cac97500bf(unittest.TestCase):
    """SocialBenefitsLocality80df32d43a5810000ce182cac97500bf unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
