# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.marital_status_information6de928ab1284100059f5dc52629b01f4 import MaritalStatusInformation6de928ab1284100059f5dc52629b01f4
from workday_person_python_sdk import configuration


class TestMaritalStatusInformation6de928ab1284100059f5dc52629b01f4(unittest.TestCase):
    """MaritalStatusInformation6de928ab1284100059f5dc52629b01f4 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
