# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.military_service_type6de928ab128410005bc12d1bc69b0230 import MilitaryServiceType6de928ab128410005bc12d1bc69b0230
from workday_person_python_sdk import configuration


class TestMilitaryServiceType6de928ab128410005bc12d1bc69b0230(unittest.TestCase):
    """MilitaryServiceType6de928ab128410005bc12d1bc69b0230 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
