# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.military_rank6de928ab128410005be5dbfb939d0234 import MilitaryRank6de928ab128410005be5dbfb939d0234
from workday_person_python_sdk import configuration


class TestMilitaryRank6de928ab128410005be5dbfb939d0234(unittest.TestCase):
    """MilitaryRank6de928ab128410005be5dbfb939d0234 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
