# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.change_contact_information_event765b18aa13af1000064a10bf37b800ed import ChangeContactInformationEvent765b18aa13af1000064a10bf37b800ed
from workday_person_python_sdk import configuration


class TestChangeContactInformationEvent765b18aa13af1000064a10bf37b800ed(unittest.TestCase):
    """ChangeContactInformationEvent765b18aa13af1000064a10bf37b800ed unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
