# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_a58f621b14ee100014b01c034eeb00f3 import UsageA58f621b14ee100014b01c034eeb00f3
from workday_person_python_sdk import configuration


class TestUsageA58f621b14ee100014b01c034eeb00f3(unittest.TestCase):
    """UsageA58f621b14ee100014b01c034eeb00f3 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
