# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country_phone_code_a58f621b14ee1000185bf335b38401cb import CountryPhoneCodeA58f621b14ee1000185bf335b38401cb
from workday_person_python_sdk import configuration


class TestCountryPhoneCodeA58f621b14ee1000185bf335b38401cb(unittest.TestCase):
    """CountryPhoneCodeA58f621b14ee1000185bf335b38401cb unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
