# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.device_type1089da0ab90910000f7089256c7b0888 import DeviceType1089da0ab90910000f7089256c7b0888
from workday_person_python_sdk import configuration


class TestDeviceType1089da0ab90910000f7089256c7b0888(unittest.TestCase):
    """DeviceType1089da0ab90910000f7089256c7b0888 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
