# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.gender414c4cee7d91100023fe32ce16e70019 import Gender414c4cee7d91100023fe32ce16e70019
from workday_person_python_sdk import configuration


class TestGender414c4cee7d91100023fe32ce16e70019(unittest.TestCase):
    """Gender414c4cee7d91100023fe32ce16e70019 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
