# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country_phone_code1089da0ab90910000f6e4de36f670883 import CountryPhoneCode1089da0ab90910000f6e4de36f670883
from workday_person_python_sdk import configuration


class TestCountryPhoneCode1089da0ab90910000f6e4de36f670883(unittest.TestCase):
    """CountryPhoneCode1089da0ab90910000f6e4de36f670883 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
