# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.relative_type_e08d883b5eae1000040cc1231a5902f5 import RelativeTypeE08d883b5eae1000040cc1231a5902f5
from workday_person_python_sdk import configuration


class TestRelativeTypeE08d883b5eae1000040cc1231a5902f5(unittest.TestCase):
    """RelativeTypeE08d883b5eae1000040cc1231a5902f5 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
