# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.media_download5d5f0fb1184b10000b16f0e5c20f0000 import MediaDownload5d5f0fb1184b10000b16f0e5c20f0000
from workday_person_python_sdk import configuration


class TestMediaDownload5d5f0fb1184b10000b16f0e5c20f0000(unittest.TestCase):
    """MediaDownload5d5f0fb1184b10000b16f0e5c20f0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
