# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.military_service_reference_aaeb64c958b2100016889fe0267e0246 import MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246
from workday_person_python_sdk import configuration


class TestMilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246(unittest.TestCase):
    """MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
