# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.ethnicity6de928ab1284100058892e53dac501d1 import Ethnicity6de928ab1284100058892e53dac501d1
from workday_person_python_sdk import configuration


class TestEthnicity6de928ab1284100058892e53dac501d1(unittest.TestCase):
    """Ethnicity6de928ab1284100058892e53dac501d1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
