# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.content_type6b9baf67ce60100011fd138066140090 import ContentType6b9baf67ce60100011fd138066140090
from workday_person_python_sdk import configuration


class TestContentType6b9baf67ce60100011fd138066140090(unittest.TestCase):
    """ContentType6b9baf67ce60100011fd138066140090 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
