# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.grade6de928ab128410005c56a5feed2e0244 import Grade6de928ab128410005c56a5feed2e0244
from workday_person_python_sdk import configuration


class TestGrade6de928ab128410005c56a5feed2e0244(unittest.TestCase):
    """Grade6de928ab128410005c56a5feed2e0244 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
