# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.local_name_ab5c028f50b310001cb4684782660256 import LocalNameAb5c028f50b310001cb4684782660256
from workday_person_python_sdk import configuration


class TestLocalNameAb5c028f50b310001cb4684782660256(unittest.TestCase):
    """LocalNameAb5c028f50b310001cb4684782660256 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
