# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.country6de928ab12841000549fe6404b2101c3 import Country6de928ab12841000549fe6404b2101c3
from workday_person_python_sdk import configuration


class TestCountry6de928ab12841000549fe6404b2101c3(unittest.TestCase):
    """Country6de928ab12841000549fe6404b2101c3 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
