# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.alternate_work_location_bdfa2c83ea5e10002b70a80a153e5d68 import AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
from workday_person_python_sdk import configuration


class TestAlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68(unittest.TestCase):
    """AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
