# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.disability_status6de928ab128410005c56a5a5299c0239 import DisabilityStatus6de928ab128410005c56a5a5299c0239
from workday_person_python_sdk import configuration


class TestDisabilityStatus6de928ab128410005c56a5a5299c0239(unittest.TestCase):
    """DisabilityStatus6de928ab128410005c56a5a5299c0239 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
