# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.disability15d8b82e323110000d98d0fc4d9903a5 import Disability15d8b82e323110000d98d0fc4d9903a5
from workday_person_python_sdk import configuration


class TestDisability15d8b82e323110000d98d0fc4d9903a5(unittest.TestCase):
    """Disability15d8b82e323110000d98d0fc4d9903a5 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
