# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.common_boolean_representation_c6cfba790def100010efb5c8ebf00000 import CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000
from workday_person_python_sdk import configuration


class TestCommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000(unittest.TestCase):
    """CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
