# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.location6de928ab1284100059cd755321a501f1 import Location6de928ab1284100059cd755321a501f1
from workday_person_python_sdk import configuration


class TestLocation6de928ab1284100059cd755321a501f1(unittest.TestCase):
    """Location6de928ab1284100059cd755321a501f1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
