# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.business_process_parameters83f6f6b7c38d100009c7ad91dd414a16 import BusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16
from workday_person_python_sdk import configuration


class TestBusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16(unittest.TestCase):
    """BusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
