# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.location80df32d43a5810000d59f391b32400d8 import Location80df32d43a5810000d59f391b32400d8
from workday_person_python_sdk import configuration


class TestLocation80df32d43a5810000d59f391b32400d8(unittest.TestCase):
    """Location80df32d43a5810000d59f391b32400d8 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
