# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.person_representation_e451ce2c8b48100007c312f3f72700b3 import PersonRepresentationE451ce2c8b48100007c312f3f72700b3
from workday_person_python_sdk import configuration


class TestPersonRepresentationE451ce2c8b48100007c312f3f72700b3(unittest.TestCase):
    """PersonRepresentationE451ce2c8b48100007c312f3f72700b3 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
