# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.salutation_suffix_e08d883b5eae10000403d7d736c102ee import SalutationSuffixE08d883b5eae10000403d7d736c102ee
from workday_person_python_sdk import configuration


class TestSalutationSuffixE08d883b5eae10000403d7d736c102ee(unittest.TestCase):
    """SalutationSuffixE08d883b5eae10000403d7d736c102ee unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
