# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.salutation11c67b72c9c610000edf7291ae7b004c import Salutation11c67b72c9c610000edf7291ae7b004c
from workday_person_python_sdk import configuration


class TestSalutation11c67b72c9c610000edf7291ae7b004c(unittest.TestCase):
    """Salutation11c67b72c9c610000edf7291ae7b004c unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
