# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_type901718dd5e7910000cc03935c73e029c import UsageType901718dd5e7910000cc03935c73e029c
from workday_person_python_sdk import configuration


class TestUsageType901718dd5e7910000cc03935c73e029c(unittest.TestCase):
    """UsageType901718dd5e7910000cc03935c73e029c unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
