# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.content_type43b30ba735b8100011ee47993f11014a import ContentType43b30ba735b8100011ee47993f11014a
from workday_person_python_sdk import configuration


class TestContentType43b30ba735b8100011ee47993f11014a(unittest.TestCase):
    """ContentType43b30ba735b8100011ee47993f11014a unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
