# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.rank6de928ab128410005b41e4ba56a6021f import Rank6de928ab128410005b41e4ba56a6021f
from workday_person_python_sdk import configuration


class TestRank6de928ab128410005b41e4ba56a6021f(unittest.TestCase):
    """Rank6de928ab128410005b41e4ba56a6021f unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
