# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.political_affiliation_bf9cd1638e0f10000a6604bfef01014a import PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a
from workday_person_python_sdk import configuration


class TestPoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a(unittest.TestCase):
    """PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
