# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.contact_usage_ab827579ee171000211397a6dede017d import ContactUsageAb827579ee171000211397a6dede017d
from workday_person_python_sdk import configuration


class TestContactUsageAb827579ee171000211397a6dede017d(unittest.TestCase):
    """ContactUsageAb827579ee171000211397a6dede017d unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
