# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.people_get_work_phones_response import PeopleGetWorkPhonesResponse
from workday_person_python_sdk import configuration


class TestPeopleGetWorkPhonesResponse(unittest.TestCase):
    """PeopleGetWorkPhonesResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
