# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.disability_certification_basis15d8b82e323110000db825167ee603a9 import DisabilityCertificationBasis15d8b82e323110000db825167ee603a9
from workday_person_python_sdk import configuration


class TestDisabilityCertificationBasis15d8b82e323110000db825167ee603a9(unittest.TestCase):
    """DisabilityCertificationBasis15d8b82e323110000db825167ee603a9 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
