# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.universal_ide451ce2c8b48100007c31392a1ff00c2 import UniversalIDE451ce2c8b48100007c31392a1ff00c2
from workday_person_python_sdk import configuration


class TestUniversalIDE451ce2c8b48100007c31392a1ff00c2(unittest.TestCase):
    """UniversalIDE451ce2c8b48100007c31392a1ff00c2 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
