# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.device_type_a58f621b14ee100018ac4d72f02901ea import DeviceTypeA58f621b14ee100018ac4d72f02901ea
from workday_person_python_sdk import configuration


class TestDeviceTypeA58f621b14ee100018ac4d72f02901ea(unittest.TestCase):
    """DeviceTypeA58f621b14ee100018ac4d72f02901ea unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
