# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.type6de928ab128410005b41e4ac0ec5021d import Type6de928ab128410005b41e4ac0ec5021d
from workday_person_python_sdk import configuration


class TestType6de928ab128410005b41e4ac0ec5021d(unittest.TestCase):
    """Type6de928ab128410005b41e4ac0ec5021d unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
