# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.uniform_service_reserve_status9503dc49ae9610001e48857455610000 import UniformServiceReserveStatus9503dc49ae9610001e48857455610000
from workday_person_python_sdk import configuration


class TestUniformServiceReserveStatus9503dc49ae9610001e48857455610000(unittest.TestCase):
    """UniformServiceReserveStatus9503dc49ae9610001e48857455610000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
