# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage6333dee5ac2010000c8653405aaa0038 import Usage6333dee5ac2010000c8653405aaa0038
from workday_person_python_sdk import configuration


class TestUsage6333dee5ac2010000c8653405aaa0038(unittest.TestCase):
    """Usage6333dee5ac2010000c8653405aaa0038 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
