# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.place_of_birth6de928ab12841000549fe623b1ab01c0 import PlaceOfBirth6de928ab12841000549fe623b1ab01c0
from workday_person_python_sdk import configuration


class TestPlaceOfBirth6de928ab12841000549fe623b1ab01c0(unittest.TestCase):
    """PlaceOfBirth6de928ab12841000549fe623b1ab01c0 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
