# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.ethnicities_for_visual_survey2b5dded3d48e10001154aae4890a0104 import EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104
from workday_person_python_sdk import configuration


class TestEthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104(unittest.TestCase):
    """EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
