# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.citizenship_status80df32d43a5810000f452a84da970114 import CitizenshipStatus80df32d43a5810000f452a84da970114
from workday_person_python_sdk import configuration


class TestCitizenshipStatus80df32d43a5810000f452a84da970114(unittest.TestCase):
    """CitizenshipStatus80df32d43a5810000f452a84da970114 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
