# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.usage_df014bc8b5fa10000b2c21c8738d00e7 import UsageDf014bc8b5fa10000b2c21c8738d00e7
from workday_person_python_sdk import configuration


class TestUsageDf014bc8b5fa10000b2c21c8738d00e7(unittest.TestCase):
    """UsageDf014bc8b5fa10000b2c21c8738d00e7 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
