# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.veterans_preference898f4bc8578c100010cc072a1b140000 import VeteransPreference898f4bc8578c100010cc072a1b140000
from workday_person_python_sdk import configuration


class TestVeteransPreference898f4bc8578c100010cc072a1b140000(unittest.TestCase):
    """VeteransPreference898f4bc8578c100010cc072a1b140000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
