# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.disability_grade15d8b82e323110000ddf3ff73d2e03ae import DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae
from workday_person_python_sdk import configuration


class TestDisabilityGrade15d8b82e323110000ddf3ff73d2e03ae(unittest.TestCase):
    """DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
