# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import unittest

import workday_person_python_sdk
from workday_person_python_sdk.model.status6de928ab1284100059f5dc66f77e01f6 import Status6de928ab1284100059f5dc66f77e01f6
from workday_person_python_sdk import configuration


class TestStatus6de928ab1284100059f5dc66f77e01f6(unittest.TestCase):
    """Status6de928ab1284100059f5dc66f77e01f6 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
