# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.action38ff08ab6736100010816009079d0126 import Action38ff08ab6736100010816009079d0126
from workday_person_python_sdk.pydantic.comments86093b8a932f10001499f356ff83012e import Comments86093b8a932f10001499f356ff83012e
from workday_person_python_sdk.pydantic.event_attachments_for_toolbar43b30ba735b8100011ee4767246d0143 import EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
from workday_person_python_sdk.pydantic.for5d688bd57bb910001815ab3dd10024a9 import For5d688bd57bb910001815ab3dd10024a9
from workday_person_python_sdk.pydantic.overall_business_process5d688bd57bb910001815ab49927724aa import OverallBusinessProcess5d688bd57bb910001815ab49927724aa
from workday_person_python_sdk.pydantic.transaction_status7457adcbe0fa1000089b63ab3a510000 import TransactionStatus7457adcbe0fa1000089b63ab3a510000

BusinessProcessParameters83f6f6b7c38d100009c69131dea04a14 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
