# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.disability_certification_basis15d8b82e323110000db825167ee603a9 import DisabilityCertificationBasis15d8b82e323110000db825167ee603a9

CertificationBasis6de928ab128410005c56a638b9d4024c = typing.Union[DisabilityCertificationBasis15d8b82e323110000db825167ee603a9,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
