# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.country_phone_code_ab827579ee1710001caa7c12047d0152 import CountryPhoneCodeAb827579ee1710001caa7c12047d0152

CountryPhoneCodeA58f621b14ee1000185bf335b38401cb = typing.Union[CountryPhoneCodeAb827579ee1710001caa7c12047d0152,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
