# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class FACETSMODELREFERENCEItemValuesItem(BaseModel):
    # wid / id / reference id
    id: str = Field(alias='id')

    # The number of instances returned by this facet
    count: typing.Optional[int] = Field(None, alias='count')

    # A description of the facet
    descriptor: typing.Optional[str] = Field(None, alias='descriptor')

    # A link to the instance
    href: typing.Optional[str] = Field(None, alias='href')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
