# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.facetsmodelreference_item_values import FACETSMODELREFERENCEItemValues

class FACETSMODELREFERENCEItem(BaseModel):
    # A description of the facet
    descriptor: typing.Optional[str] = Field(None, alias='descriptor')

    # The alias used to select the facet
    facet_parameter: typing.Optional[str] = Field(None, alias='facetParameter')

    values: typing.Optional[FACETSMODELREFERENCEItemValues] = Field(None, alias='values')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
