# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.political_affiliation6de928ab128410005b04f3329eee0214 import PoliticalAffiliation6de928ab128410005b04f3329eee0214

PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a = typing.Union[PoliticalAffiliation6de928ab128410005b04f3329eee0214,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
