# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.common_boolean_representation_c6cfba790def100010efb5c8ebf00000 import CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000

SelectiveServiceRegistrationCa34e5d6a47710000f902f4d90240000 = typing.Union[CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
