# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.military_service_type6de928ab128410005bc12d1bc69b0230 import MilitaryServiceType6de928ab128410005bc12d1bc69b0230

Type6de928ab128410005b41e4ac0ec5021d = typing.Union[MilitaryServiceType6de928ab128410005bc12d1bc69b0230,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
