# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_person_python_sdk.pydantic.alternate_work_location_bdfa2c83ea5e10002b70a80a153e5d68 import AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
from workday_person_python_sdk.pydantic.business_process_parameters_bdfa2c83ea5e10002b873037350f5d6c import BusinessProcessParametersBdfa2c83ea5e10002b873037350f5d6c

WorkContactChangeEventViewBdfa2c83ea5e10002b70a7e9f69e5d67 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
