# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from workday_person_python_sdk.paths.countries_id_address_components.get import GetAddressComponents
from workday_person_python_sdk.paths.countries.get import GetCollectionInformation
from workday_person_python_sdk.paths.countries_id.get import GetInfo
from workday_person_python_sdk.paths.countries_id_name_components.get import GetNameComponents
from workday_person_python_sdk.apis.tags.countries_api_raw import CountriesApiRaw


class CountriesApi(
    GetAddressComponents,
    GetCollectionInformation,
    GetInfo,
    GetNameComponents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CountriesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CountriesApiRaw(api_client)
