# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from workday_person_python_sdk.paths.home_contact_information_changes_id_email_addresses.post import CreateEmailAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_instant_messengers.post import CreateInstantMessengerRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_addresses.post import CreateNewAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_phone_numbers.post import CreatePhoneNumberRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_web_addresses.post import CreateWebAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_addresses_subresource_id.get import GetAddressAsStagedRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_addresses.get import GetAddressesStagedRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_email_addresses_subresource_id.get import GetEmailAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id.get import GetEventInformationRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_instant_messengers_subresource_id.get import GetInstantMessengerRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_phone_numbers.get import GetPhoneNumbersRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_email_addresses.get import GetStagedEmailAddressesRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_instant_messengers.get import GetStagedInstantMessengersRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_phone_numbers_subresource_id.get import GetStagedPhoneNumberRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_web_addresses_subresource_id.get import GetWebAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_web_addresses.get import GetWebAddressesStagedRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_addresses_subresource_id.delete import RemoveAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_email_addresses_subresource_id.delete import RemoveEmailAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_instant_messengers_subresource_id.delete import RemoveInstantMessengerRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_phone_numbers_subresource_id.delete import RemovePhoneNumberRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_web_addresses_subresource_id.delete import RemoveWebAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_submit.post import SubmitChangeRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_addresses_subresource_id.put import UpdateAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_email_addresses_subresource_id.patch import UpdateEmailAddressRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_instant_messengers_subresource_id.patch import UpdateInstantMessengerRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_phone_numbers_subresource_id.patch import UpdatePhoneNumberRaw
from workday_person_python_sdk.paths.home_contact_information_changes_id_web_addresses_subresource_id.patch import UpdateWebAddressRaw


class HomeContactInformationChangesApiRaw(
    CreateEmailAddressRaw,
    CreateInstantMessengerRaw,
    CreateNewAddressRaw,
    CreatePhoneNumberRaw,
    CreateWebAddressRaw,
    GetAddressAsStagedRaw,
    GetAddressesStagedRaw,
    GetEmailAddressRaw,
    GetEventInformationRaw,
    GetInstantMessengerRaw,
    GetPhoneNumbersRaw,
    GetStagedEmailAddressesRaw,
    GetStagedInstantMessengersRaw,
    GetStagedPhoneNumberRaw,
    GetWebAddressRaw,
    GetWebAddressesStagedRaw,
    RemoveAddressRaw,
    RemoveEmailAddressRaw,
    RemoveInstantMessengerRaw,
    RemovePhoneNumberRaw,
    RemoveWebAddressRaw,
    SubmitChangeRaw,
    UpdateAddressRaw,
    UpdateEmailAddressRaw,
    UpdateInstantMessengerRaw,
    UpdatePhoneNumberRaw,
    UpdateWebAddressRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
