# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from workday_person_python_sdk.paths.people_id_additional_names_subresource_id.get import GetAdditionalNameRaw
from workday_person_python_sdk.paths.people_id_additional_names.get import GetAdditionalNamesRaw
from workday_person_python_sdk.paths.people_id.get import GetByIdRaw
from workday_person_python_sdk.paths.people_id_home_addresses_subresource_id.get import GetHomeAddressRaw
from workday_person_python_sdk.paths.people_id_home_addresses.get import GetHomeAddressesRaw
from workday_person_python_sdk.paths.people_id_home_emails_subresource_id.get import GetHomeEmailRaw
from workday_person_python_sdk.paths.people_id_home_emails.get import GetHomeEmailsRaw
from workday_person_python_sdk.paths.people_id_home_instant_messengers_subresource_id.get import GetHomeInstantMessengerUsernameRaw
from workday_person_python_sdk.paths.people_id_home_instant_messengers.get import GetHomeInstantMessengersRaw
from workday_person_python_sdk.paths.people_id_home_phones_subresource_id.get import GetHomePhoneRaw
from workday_person_python_sdk.paths.people_id_home_phones.get import GetHomePhonesRaw
from workday_person_python_sdk.paths.people_id_home_web_addresses_subresource_id.get import GetHomeWebAddressRaw
from workday_person_python_sdk.paths.people_id_home_web_addresses.get import GetHomeWebAddressesRaw
from workday_person_python_sdk.paths.people_id_legal_name_subresource_id.get import GetLegalNameRaw
from workday_person_python_sdk.paths.people_id_legal_name.get import GetLegalName0Raw
from workday_person_python_sdk.paths.people_id_audio_name_pronunciation_subresource_id.get import GetNamePronunciationRaw
from workday_person_python_sdk.paths.people_id_audio_name_pronunciation.get import GetNamePronunciationsRaw
from workday_person_python_sdk.paths.people.get import GetPersonByIdRaw
from workday_person_python_sdk.paths.people_id_personal_information.get import GetPersonalInfoRaw
from workday_person_python_sdk.paths.people_id_personal_information_subresource_id.get import GetPersonalInfo0Raw
from workday_person_python_sdk.paths.people_id_photos_subresource_id.get import GetPersonalPhotoRaw
from workday_person_python_sdk.paths.people_id_photos.get import GetPersonalPhotosRaw
from workday_person_python_sdk.paths.people_id_preferred_name.get import GetPreferredNameRaw
from workday_person_python_sdk.paths.people_id_preferred_name_subresource_id.get import GetPreferredName0Raw
from workday_person_python_sdk.paths.people_id_public_contact_information_subresource_id.get import GetPublicContactInformationRaw
from workday_person_python_sdk.paths.people_id_public_contact_information.get import GetPublicContactInformation0Raw
from workday_person_python_sdk.paths.people_id_work_addresses_subresource_id.get import GetWorkAddressRaw
from workday_person_python_sdk.paths.people_id_work_addresses.get import GetWorkAddressesRaw
from workday_person_python_sdk.paths.people_id_work_emails_subresource_id.get import GetWorkEmailRaw
from workday_person_python_sdk.paths.people_id_work_emails.get import GetWorkEmailsRaw
from workday_person_python_sdk.paths.people_id_work_instant_messengers_subresource_id.get import GetWorkInstantMessengerUsernameRaw
from workday_person_python_sdk.paths.people_id_work_instant_messengers.get import GetWorkInstantMessengerUsernamesRaw
from workday_person_python_sdk.paths.people_id_work_phones_subresource_id.get import GetWorkPhoneRaw
from workday_person_python_sdk.paths.people_id_work_phones.get import GetWorkPhonesRaw
from workday_person_python_sdk.paths.people_id_work_web_addresses_subresource_id.get import GetWorkWebAddressRaw
from workday_person_python_sdk.paths.people_id_work_web_addresses.get import GetWorkWebAddressesRaw


class PeopleApiRaw(
    GetAdditionalNameRaw,
    GetAdditionalNamesRaw,
    GetByIdRaw,
    GetHomeAddressRaw,
    GetHomeAddressesRaw,
    GetHomeEmailRaw,
    GetHomeEmailsRaw,
    GetHomeInstantMessengerUsernameRaw,
    GetHomeInstantMessengersRaw,
    GetHomePhoneRaw,
    GetHomePhonesRaw,
    GetHomeWebAddressRaw,
    GetHomeWebAddressesRaw,
    GetLegalNameRaw,
    GetLegalName0Raw,
    GetNamePronunciationRaw,
    GetNamePronunciationsRaw,
    GetPersonByIdRaw,
    GetPersonalInfoRaw,
    GetPersonalInfo0Raw,
    GetPersonalPhotoRaw,
    GetPersonalPhotosRaw,
    GetPreferredNameRaw,
    GetPreferredName0Raw,
    GetPublicContactInformationRaw,
    GetPublicContactInformation0Raw,
    GetWorkAddressRaw,
    GetWorkAddressesRaw,
    GetWorkEmailRaw,
    GetWorkEmailsRaw,
    GetWorkInstantMessengerUsernameRaw,
    GetWorkInstantMessengerUsernamesRaw,
    GetWorkPhoneRaw,
    GetWorkPhonesRaw,
    GetWorkWebAddressRaw,
    GetWorkWebAddressesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
