# coding: utf-8

"""
    person

    The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from workday_person_python_sdk.paths.phone_validation.post import ValidatePhoneNumber
from workday_person_python_sdk.apis.tags.phone_validation_api_raw import PhoneValidationApiRaw


class PhoneValidationApi(
    ValidatePhoneNumber,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PhoneValidationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PhoneValidationApiRaw(api_client)
